# Generated by Django 4.2.11 on 2024-11-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('billing', 'Billing Issue'), ('technical', 'Technical Issue'), ('product', 'Product Issue'), ('other', 'Other')], max_length=20)),
                ('issue_description', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wabaApp.customer')),
            ],
        ),
    ]
