# Generated by Django 4.2.11 on 2024-11-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
