# Generated by Django 4.2.11 on 2024-11-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0002_remove_order_customer_remove_order_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
