# Generated by Django 4.2.11 on 2024-11-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0002_rename_fullname_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
