# Generated by Django 4.2.11 on 2024-11-29 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('billing', 'Billing Issue'), ('technical', 'Technical Issue'), ('product', 'Product Issue'), ('other', 'Other')], max_length=50)),
                ('issue_description', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wabaApp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
