# Generated by Django 4.2.11 on 2024-11-29 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0003_customerreport_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default=datetime.datetime(2024, 11, 29, 23, 1, 45, 764196, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=datetime.datetime(2024, 11, 29, 23, 1, 55, 547555, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
