# Generated by Django 4.2.11 on 2024-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0004_payment_payment_method_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prepaid_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
