# Generated by Django 4.2.11 on 2024-11-26 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0005_product_customer_created_at_sale_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 22, 52, 8, 99607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
