# Generated by Django 4.2.11 on 2024-12-05 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0005_customer_prepaid_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 12, 5, 9, 43, 32, 992296, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 9, 43, 52, 193771, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=datetime.datetime(2024, 12, 5, 9, 44, 1, 663897, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
