# Generated by Django 4.2.11 on 2024-11-25 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0005_waterusage_prepaidbalance_payment_meterstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidbalance',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 11, 25, 14, 28, 52, 566278, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterusage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waterusage',
            name='usage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='MeterStatus',
        ),
    ]
