# Generated by Django 4.0 on 2025-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0006_rename_employee_id_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, to='wabaApp.Product'),
        ),
    ]
