# Generated by Django 4.2.11 on 2024-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, to='wabaApp.product'),
        ),
    ]
