# Generated by Django 4.2.11 on 2024-11-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wabaApp.customer'),
        ),
    ]
