# Generated by Django 4.2.11 on 2024-11-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wabaApp', '0008_customer_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wabaApp.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wabaApp.sale')),
            ],
        ),
    ]
